
export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_ABOUT = "PAGE_ABOUT";
export const PAGE_USER_REGISTRATION = "PAGE_USER_REGISTRATION";
export const PAGE_DASHBOARD = "PAGE_DASHBOARD";
export const PAGE_PROJECT_DETAILS = "PAGE_PROJECT_DETAILS";


export const SUB_PAGE_TIMELINE = "SUB_PAGE_TIMELINE";
export const SUB_PAGE_CALENDAR = "SUB_PAGE_CALENDAR";
export const SUB_PAGE_NEW_TASK = "SUB_PAGE_NEW_TASK";
export const SUB_PAGE_NEW_MEETING = "SUB_PAGE_NEW_MEETING";
export const SUB_PAGE_NEW_MILESTONE = "SUB_PAGE_NEW_MILESTONE";
export const SUB_PAGE_THIS_WEEK_PLAN = "SUB_PAGE_THIS_WEEK_PLAN";
export const SUB_PAGE_EDIT_PROJECT = "SUB_PAGE_EDIT_PROJECT";
